export const GET_RESTAURANT_DATA_REQUEST = "GET_RESTAURANT_DATA_REQUEST";
export const GET_RESTAURANT_DATA_SUCCESS = "GET_RESTAURANT_DATA_SUCCESS";
export const GET_RESTAURANT_DATA_FAILURE = "GET_RESTAURANT_DATA_FAILURE";

export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const SORT_BY_RATING = "SORT_BY_RATING";
