export const GET_CAPSULES_DATA_REQUEST = "GET_CAPSULES_DATA_REQUEST";
export const GET_CAPSULES_DATA_SUCCESS = "GET_CAPSULES_DATA_SUCCESS";
export const GET_CAPSULES_DATA_FAILURE = "GET_CAPSULES_DATA_FAILURE";

export const FILTER_BY_STATUS = "FILTER_BY_STATUS";
export const FILTER_BY_ORIGINAL_LAUNCH = "FILTER_BY_ORIGINAL_LAUNCH";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
